name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: ['3.3.0']

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@360dc864d5da99d54fcb8e9148c14a84b90d3e88
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: gem install
        run: |
          gem install parallel
          export RUBY_YJIT_ENABLE=1
          export RUBYOPT=--yjit
          echo $(ruby -e 'p RubyVM::YJIT.enabled?') 1>&2
      - name: Build
        run: |
          mkdir -p release
          (cd src; bash make.sh)
          (cd userdic; bash mkdict.sh)
          ls release 1>&2
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          omitBody: true
          artifacts: 'release/*'
          token: ${{ secrets.GITHUB_TOKEN }}
