name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:

    runs-on: ubuntu-latest
    env:
      RUSTC_WRAPPER: sccache
      SCCACHE_CACHE_SIZE: 1G
      SCCACHE_DIR: /home/runner/.cache/sccache
      # SCCACHE_RECACHE: 1 # Uncomment this to clear cache, then comment
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          submodules: 'recursive'
      - name: install build tools (Linux)
        run: |
          # uv
          curl -LsSf https://astral.sh/uv/install.sh | sh
          source $HOME/.cargo/env || PATH=$HOME/.cargo/bin:$PATH
          uv venv -p 3.12
          uv pip install jaconv
          rm -f ~/.cargo/config*
      - name: Build
        run: |
          source .venv/bin/activate
          mkdir -p release
          (cd userdic; bash mkdict.sh)
          ls release 1>&2
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          omitBody: true
          artifacts: 'release/*'
          token: ${{ secrets.GITHUB_TOKEN }}
